spring:
  jpa:
    open-in-view: false
    database: MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE}?createDatabaseIfNotExist=true
    username: ${USERNAME}
    password: ${PASSWORD}