spring:
  jpa:
    open-in-view: false
    database: H2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: tests
    password: '123'
    port: 8090
    h2:
      console:
        enabled: 'true'
        settings:
          trace: 'false'
        path: /h2-console
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect