version: '3.8'
services:
  db:
    container_name: mysql-db
    image: mysql
    volumes:
      - mysql_db_data:/var/lib/mysql
    restart: always
    env_file:
      - config/.env
volumes:
  mysql_db_data: { }